### PR TITLE
Debian 8.7 update

### PR DESCRIPTION
**Pull request by ek9**
Updates Debian box to 8.7

### CODE REVIEW

**Comment by kaorimatz** [comment]
Hi @ek9, thank you for the patch. It seems that debian-cd team released 8.7.1 [1] today. Could you update your patch to use 8.7.1 image?

[1] http://cdimage.debian.org/debian-cd/8.7.1/

**Comment by ek9** [comment]
Done!

**Comment by ek9** [comment]
Please don't merge, there are problems with the checksum. Trying to find out why.

**Comment by kaorimatz** [comment]
LGTM. Thanks a lot!

**Pull request merged**
